version: 1.0.0-alpha-{build}
nuget:
  project_feed: true
before_build:
- ps: >-
    .\Patch-ProjectJson.ps1 $env:APPVEYOR_BUILD_VERSION

    dnvm upgrade -r clr

    dnu restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
test_script:
- cmd: dnx -p test/SimpleHtmlTemplater.Test test
artifacts:
- path: artifacts\bin\**\**\*.nupkg